
CREATE FUNCTION [util].[GetRange](@RowCount INT)
RETURNS TABLE
AS
RETURN
WITH
	Range10 AS
	(
		SELECT I=0 UNION ALL SELECT I=1 UNION ALL SELECT I=2 UNION ALL SELECT I=3 UNION ALL SELECT I=4
		UNION ALL
		SELECT I=5 UNION ALL SELECT I=6 UNION ALL SELECT I=7 UNION ALL SELECT I=8 UNION ALL SELECT I=9
	)
SELECT TOP(@RowCount) RN = -1 + ROW_NUMBER() OVER(ORDER BY (SELECT 1)) FROM Range10 R1, Range10 R2, Range10 R3, Range10 R4, Range10 R5, Range10 R6
/*
SELECT * FROM util.GetRange(123) T ORDER BY 1;
*/
;